---
title: "Untitled"
author: "AE"
date: "5/29/2021"
output: html_document
runtime: shiny
---

```{r setup, include=T}
library(shiny)
library(miniUI)

ui <-shinyUI(fluidPage(
    titlePanel("Predict Swiss Fertility"),
    sidebarLayout(
        #contains input sent to server
        sidebarPanel(
            sliderInput("sliderAG", "What is the Fertility rate?:",            #get a slider input called 'sliderAG'
                        min = 0,
                        max = 90,
                        value = 10), #start value
            #two checkboxes for whether it will show that particular model output
            checkboxInput("showMode11","Show/Hide Model",value=T),            #showModel11 is an input
            submitButton("Submit")                                               #this allows a delayed reactivity so that you have to click a submit button on UI to re-run calc, otherwise it always calculated automatically once you change the input value on the slider. 
        ),
        
        # contains output
        mainPanel(
            plotOutput("plot1"),                                                #look in server for plot labeled plot1 to display
            
            h3("Predicted Swiss Fertility from Model:"),
            textOutput("pred1")                                           #output from prediction in server labelled pred1
            
        )
    )
))


server <- function(input, output) {
    
    
    model11<-lm(Fertility ~ Agriculture , data = swiss) #red line
    
    #get prediction for model 1
    model1pred<-reactive({               #since we are doing calcs based on inputted values from UI, it needs to be reactive
        mpgInput<-input$sliderAG        #sliderAG is what we named the sliderInput value in the UI
        predict(model11,data.frame(Agriculture=mpgInput)) #predict using new value input from slider
    })
    
    
    
    #create outputs
    output$plot1 <- renderPlot({           #remember UI is looking for a plot called 'plot1'
        mpgInput<-input$sliderAG           #grab the input from the slider
        plot(swiss$Agriculture,swiss$Fertility,xlab = "Agriculture", ylab="Fertility")  #plot all mpg vs hp
        #{abline(model11,col="red")}
        model12lines<-predict(model11,data.frame(Agriculture=0:90))
        
        lines(0:90,model12lines,col="blue")
    })
    
    output$pred1<-renderText({model1pred()}) #need the parentheses after 'model1pred' bc it is from a reactive expression. if you don't have the parenthesis it will return the function, not the number/points
    
    
}

```

```{r run, include=T}
shinyApp(ui = ui, server = server)

```

